### ISSUE TITLE
请问 local_cache_sync的性能如何

### ISSUE THREAD

**Issue by zackhsuan** [mjl0602/local_cache_sync#2]
非常感谢你的dart库
正在寻找一个轻量级可做缓存的封装
大概阅读了一下实现方案, 应该是json字符串化的文本文件的读取写入
不知道对性能方便有什么想法么

**Comment by mjl0602** [comment]
你好，如果需要在io密集场景使用，或者需要做一些复杂的关联查询，还是推荐使用sqlite进行本地储存。

开发这个库的目的，就是为了方便快速的储存数据到本地，这些数据通常都非常轻量级，不必使用数据库进行管理，即使同步存取也不会显得缓慢。而使用官方的SharePreference会导致代码变得很复杂，所以使用local_cache_sync缓存数据会提升编码体验，同时也使得其不适用于io密集型场景，因为同步任务无法并发，且会阻塞当前线程。

**Comment by mjl0602** [comment]
本库对性能的唯一优化在于LocalCacheObject的懒加载，拿整列数据时，一开始只是拿到他们的文件名，进行value的getter取值时，才去读取具体数据，这样可以在读取长列表时显著增强性能，不必一次加载数百个文件。

**Comment by zackhsuan** [comment]
谢谢你的回复
了解了 感谢. 我目前只有打算存储一些接口的本地缓存数据. 使用数据库在开发方面不够轻量, 我觉得你的这个库相对来说还比较符合我们的需求.
